language: scala

scala:
   - 2.12.8
   - 2.13.0

jdk: oraclejdk8

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier

dist: trusty